### ISSUE TITLE
xWebAppPoolDefaults missing bunch of settings

### ISSUE THREAD

**Issue by artisticcheese** [dsccommunity/xWebAdministration#105]
Is it expected or I'm missing something. Total number of parameters shall be the same as xWebAppPool since those are inherited for any knewly created apppool.

**Comment by tysonjhayes** [comment]
What version of the module are you using? 1.8.0.0 added a bunch of parameters, if there are still more that are missing could you point out which ones you feel should be there?

**Comment by artisticcheese** [comment]
All application pool settings are missing. Every single one of them. Below are the only one available.


xWebAppPoolDefaults [String] #ResourceName
{
    ApplyTo = [string]{ Machine }
    [DependsOn = [string[]]]
    [IdentityType = [string]{ ApplicationPoolIdentity | LocalService | LocalSystem | NetworkService }]
    [ManagedRuntimeVersion = [string]{  | v2.0 | v4.0 }]
    [PsDscRunAsCredential = [PSCredential]]
}

**Comment by tysonjhayes** [comment]
Sorry that was my bad, I misread the resource name.

Yes it's expected at this time, though we are open to PRs on improving this!

**Comment by artisticcheese** [comment]
Every application pool setting from xWebAppPool shall be part of this setting. So please consider adding them. Those values are inherited when new pools are created.

**Comment by artisticcheese** [comment]
Also what property ApplyTo does for xWebAppDefaults?

**Comment by onurbiyik** [comment]
Now that this issue is closed, Is this feature not going to be implemented at all? or is there a different approach?

**Comment by artisticcheese** [comment]
Nobody worked on it for last 2 years, what's the point of having it open? Hence I closed it.

**Comment by johlju** [comment]
@onurbiyik @artisticcheese Reopening this issue since there are PR that has been proposed for this.
