### ISSUE TITLE
Inconsistent Logic in Test-TargetResource for xWebsite

### ISSUE THREAD

**Issue by tysonjhayes** [dsccommunity/xWebAdministration#221]
In Test-TargetResource we see two different ways of saying the desired state is false.

[L852](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L852)

``` powershell
        # Check Physical Path property
        if ([String]::IsNullOrEmpty($PhysicalPath) -eq $false -and `
            $website.PhysicalPath -ne $PhysicalPath)
        {
            $inDesiredState = $false
            Write-Verbose -Message ($LocalizedData.VerboseTestTargetFalsePhysicalPath `
                                    -f $Name)
        }
```

and [L993](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L993)

``` powershell
        if ($PSBoundParameters.ContainsKey('LogFlags') -and `
            (-not (Compare-LogFlags -Name $Name -LogFlags $LogFlags)))
        {
            Write-Verbose -Message ($LocalizedData.VerboseTestTargetFalseLogFlags)
            return $false
        }
```

Nothing is logically wrong with these, as the $inDesiredState will eventually return.  However, it seems inconsistent and something we should consider fixing up.

Personally I'm a fan of the second process as there is no sense in spending any more time checking resources when one is already wrong.

**Comment by SNikalaichyk** [comment]
@tysonjhayes ,
I personally prefer the first approach. Checking all the properties is useful for troubleshooting, verbose logging, and scenarios where the **Invoke-DscResource** cmdlet is used.

```powershell

$xWebsiteProperties = @{
    Ensure = 'Present'
    Name = 'TestSite'
    PhysicalPath = 'C:\inetpub\wwwroot'
    ApplicationPool = 'TestAppPool'
    State = 'Started'
}

Invoke-DscResource -ModuleName xWebAdministration -Name xWebsite -Method Test -Property $xWebsiteProperties -Verbose

<...>

VERBOSE: [SNWKS01]:                            [DSCEngine] Importing the module C:\Program Files\WindowsPowerShell\Modules\xWebAdministration\1.13.0.0\DscResources\MSFT_xWebsite\MSFT_xWebsite.psm1 in force mode.
VERBOSE: [SNWKS01]: LCM:  [ Start  Test     ]  [[xWebsite]DirectResourceAccess]  
VERBOSE: [SNWKS01]:                            [[xWebsite]DirectResourceAccess] Importing the module MSFT_xWebsite in force mode.
VERBOSE: [SNWKS01]:                            [[xWebsite]DirectResourceAccess] Physical Path of website "TestSite" does not match the desired state.
VERBOSE: [SNWKS01]:                            [[xWebsite]DirectResourceAccess] The state of website "TestSite" does not match the desired state.
VERBOSE: [SNWKS01]:                            [[xWebsite]DirectResourceAccess] Application Pool for website "TestSite" does not match the desired state.
VERBOSE: [SNWKS01]:                            [[xWebsite]DirectResourceAccess] The target resource is not in the desired state.
VERBOSE: [SNWKS01]: LCM:  [ End    Test     ]  [[xWebsite]DirectResourceAccess] False in 0.2650 seconds.

<...>

InDesiredState 
-------------- 
False          

```

**Comment by johlju** [comment]
I agree with @SNikalaichyk that the first approach seems better, more information is better than less information. Show the user all properties that differ from desired state.

**Comment by RandomNoun7** [comment]
I'll go ahead and claim this one and put up the PR in the next few days.

**Comment by RandomNoun7** [comment]
I agree that the second method for setting the `$inDesiredState` variable and just writing a verbose message and moving on is better, but I think the first method's style of checking for bound parameters vs checking for a null or empty string is cleaner. So I think the final result should be a hybrid of the too like this.
```powershell
if ($PSBoundParameters.ContainsKey('LogFlags') -and `
   (-not (Compare-LogFlags -Name $Name -LogFlags $LogFlags)))
{
  $inDesiredState = $false
  Write-Verbose -Message ($LocalizedData.VerboseTestTargetFalseLogFlags)
}
```
Unless there are objections I will make all of the property tests conform to this style.

**Comment by johlju** [comment]
That’s sounds good to me at least. :)
