### ISSUE TITLE
Returns wrong thumbprint when using "Subject" as certificate identifier

### ISSUE THREAD

**Issue by FabianHubX** [dsccommunity/xWebAdministration#333]
Config:

```powershell   xWebsite SetWebSiteBinding {
        Name = 'MyWebiste'
        BindingInfo = MSFT_xWebBindingInformation
        {
            Protocol              = 'https'
            Port                  = '443'
            CertificateStoreName  = 'MY'
            CertificateSubject    = 'WebShop.contoso.com'
            HostName              = '*'
            IPAddress             = '*'
        }
    }
```
If multiple certificates with the same subject are found, the returned thumbprint is a merge of all found certificates.

Error message:

> PowerShell DSC resource MSFT_xWebsite  failed to execute Set-TargetResource functionality with error message: Failure to add certificate to web binding. Please make sure that the certificate thumbprint
"0F26652D3DB7152F6B575E53D85B8B80BBDD3603 BC80F9BF4E861EA972F0B88644AFA5ECD90B4C2D" is valid. Error: "Value does not fall within the expected range.".
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**Comment by vidarw** [comment]
Come on Microsoft! How is this still not solved after almost two years?
@SteveL-MSFT @johlju  If I commit a fix to this problem, at what pace can I expect a review and new package release?

Suggested solutions:

1) Correct the functionality of Find-Certificate to return a single certificate (as name suggests):
https://github.com/dsccommunity/xWebAdministration/blob/master/source/Modules/xWebAdministration.Common/xWebAdministration.Common.psm1#L787:

```powershell
 $certs = $certs | Sort-Object -Descending -Property 'NotAfter' | Select-Object -First 1
```

2) OR if the `Find-Certificate` is supposed to return multiple certificates, correct the issue directly in xWebSite.psm:
https://github.com/dsccommunity/xWebAdministration/blob/master/source/DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1#L1477

```powershell
$Certificate = Find-Certificate @FindCertificateSplat  | Select-Object -First 1
```

**Comment by johlju** [comment]
You are more than welcome to send in a pull request. 🙂 I will review it as soon as I have time (depending on day job and family), As soon as a commit is merged to master a preview release will be released. We can release a new full version shortly after that.

For my reference, this was worked on here but was abandoned: https://github.com/dsccommunity/xWebAdministration/pull/334/files 

Btw. The DSC module is not part of the [DSC Community](https://dsccommunity.org), no longer owned my Microsoft. That is in part why we can release so fast now. 😃

**Comment by johlju** [comment]
Oh, I suggest alternative 2 since it looks like Find-Certificate is meant to return more than one certificate. Looked at the function over at [CertificateDsc](https://github.com/dsccommunity/CertificateDsc/blob/c2006bb06f58ae4c4a3434a82acf2ea2ada81a0d/Modules/CertificateDsc.Common/CertificateDsc.Common.psm1#L801-L804) and it does the same, so let's change xWebSite.

**Comment by vidarw** [comment]
@johlju Thanks for your response. I've created a pull request where I have fixed the issue and created a new unit test to demonstrate the issue. Hopefully this can be reviewed and released in the near future :)

**Comment by johlju** [comment]
@vidarw Pushed a new release so should be available within the hour.

**Comment by vidarw** [comment]
Thanks a lot for the quick responses and fast review process! :)
