### ISSUE TITLE
Azure DevOps is removing older build images

### ISSUE THREAD

**Issue by johlju** [dsccommunity/xWebAdministration#565]
The Windows Server Core 1803 image and Windows Server2012 R2 image are being removed on March 23, 2020. This repository is using both, and they must be removed or transition to another image as appropriate.

https://github.com/dsccommunity/xWebAdministration/blob/59e8dcc945b16c59fba3c408936599b42d8f9dcf/azure-pipelines.yml#L78

https://github.com/dsccommunity/xWebAdministration/blob/59e8dcc945b16c59fba3c408936599b42d8f9dcf/azure-pipelines.yml#L119

**Comment by RandomNoun7** [comment]
Partially addressed by #567.
The associated PR #568 removed the second line, but in what appears to be some kind of mistake, left one of the steps running the `win1803` image. A new PR against the same issue will be up shortly to address that oversight.
